version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    ports:
    - "3000:3000"
    volumes:
    - ../app/environment/hello_app:/app
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    tty: true
    ports:
    - "3001:3000"
    volumes:
    - ../app/environment/toy_app:/app

